version: '3'

networks:
  localhost:
    #name: my_network

volumes:
  MariaDB_data:
    name: mariaDB
    driver: bridge
    driver_opts:
      o: bind
      type: none
      device: /home/mdelwaul/data/
  wordPressPHP_data:
    name: wp
    driver: bridge
    driver_opts:
      o: bind
      type: none
      device: /home/mdelwaul/data

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - localhost
    restart: unless-stopped
    build: ./requirements/nginx
  
  wordpress:
    image: wordpress
    container_name: wordpress
    networks:
      - localhost
    depends_on:
      - mariadb
      - nginx
    volumes:
      - wordPressPHP_data:/var/www/html
    restart: unless-stopped
    build: ./requirements/wordPressPHP --build-arg ADMIN_USER="correcteur" --build-arg ADMIN_PW=mdpcorrecteur --build-arg ADMIN_email=correcteur@student.42.fr

  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - localhost
    depends_on:
      - nginx
    volumes:
      - MariaDB_data:/var/lib/mysql
    restart: unless-stopped
    build: ./requirements/MariaDB

