version: '3'

networks:
  localhost:
    #name: my_network

volumes:
  MariaDB_data:
    name: mariaDB
    # driver: bridge
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: /sgoinfre/goinfre/Perso/mdelwaul/data_mb
  wordPressPHP_data:
    name: wp
    # driver: bridge
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: /sgoinfre/goinfre/Perso/mdelwaul/data_wp

services:
  nginx:
    depends_on:
      - wordpress
    image: nginx
    container_name: nginx
    ports:
      - "4433:443"
    networks:
      - localhost
    restart: unless-stopped
    volumes:
      - wordPressPHP_data:/var/www/wordpress
    build: ./requirements/nginx
  
  wordpress:
    image: wordpress
    container_name: wordpress
    networks:
      - localhost
    depends_on:
      - mariadb
    volumes:
      - wordPressPHP_data:/var/www/wordpress
    restart: unless-stopped
    environment:
      - ADMIN_USER=correcteur
      - ADMIN_PW=mdpcorrecteur4*
      - USER_USER=user
      - USER_PW=mdpUser4*
      - ADMIN_email=correcteur@student.42.fr
    ports:
      - "9000:9000"
    build: ./requirements/wordPressPHP

  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - localhost
    volumes:
      - MariaDB_data:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    build: ./requirements/MariaDB

