version: '3'

networks:
  localhost:
    #name: my_network

volumes:
  MariaDB_data:
    #name: MariaDB
    driver: bridge
    driver_opts:
      o: bind
      type: none
  wordPressPHP_data:
    #name: MariaDB
    driver: bridge
    driver_opts:
      o: bind
      type: none

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - localhost
    restart: always
    build: ./nginx
  
  wordPressPHP:
    image: wordPressPHP
    container_name: WordPress
    networks:
      - localhost
    depends_on:
      - MariaDB
      - nginx
    volumes:
      - wordPressPHP_data:/var/www/html
    restart: always
    build: ./wordPressPHP

  MariaDB:
    image: MariaDB
    container_name: MariaDB
    networks:
      - localhost
    depends_on:
      - nginx
    volumes:
      - MariaDB_data:/var/lib/mysql
    restart: always
    build: ./MariaDB

